<div class="box content_item">
	<div class="content_item_main">
		<div class="newsitem">
			<h2>WHAT IS OPERATION BRAVEHEART?</h2>		
			<p>Operation Braveheart will be a series of events rallies and concerts in support of our servicemen and women. These will be held around the South West, and Devon in the first instance will lead the way to start with, but my hope is that many people will take up the banner from around the country and help me to also make things happen all over the UK.</p>		
			<p>These will take the form of musical events with pop bands, stars and celebrities, and shows which I hope schools and colleges will put on. MP's and other speakers will I hope be taking part, also the public will be taking a big part in these events by coming along to, to listen to the singers and bands playing their hearts out, and listening to the speakers.</p>		
			<h2>MISSION STATEMENT</h2>
			<p>The day of the 27th of February 2007 brought to an end the life of a wonderful young man, and dedicated soldier of 2rifles regiment, Daniel Lee Coffey. Age just 21 it also brought with it a huge resolve, a resolve to fight for truth and for justice.</p>
			<p>To fight for truth for the people of this country and fight for justice for those who have given the ultimate sacrifice of their lives, OUR SERVICEMEN &amp; WOMEN. To fight for justice, for those who have been injured, both in body and mind, and to fight for those still in Iraq and Afghanistan fighting this most unholiest of wars in this countries name.</p>		
			<p>Operation Braveheart is a mission crusade, started by David Godfrey, the grandfather of Daniel, in his memory, for our dedicated servicemen and women of the Rifles and all regiments, who, in the face of battle have been, and still are, ill equipped and prepared, for such events as these.</p>
			<p>The Governance of this our country, must learn much from the mistakes made, and should admit to making them, then maybe we can all move on to make things better for our country, our people, and the world we live in, and try to make Britain great again, as she once was.</p>
			<h2>WHAT WILL OPERATION BRAVEHEART ACHIEVE?</h2>
			<p>Through Operation Braveheart, I hope we will achieve much. Firstly, by bringing our people together in support of our most valuable of assets, our dedicated servicemen and women we can do much to support them and their families.</p>
			<p>By your participation, in coming along to these events, either by purchasing an entry ticket, and/or making donations to the crusade appeal fund. I hope that together, we will raise many thousands of pounds to get help to those who are in need of support</p>
			<h2>WHERE WILL THE MONEY RAISED GO?</h2>
			<p>All funds raised through entry ticket fees and donations, will go into a special account which will be created, and operated independently of David Godfrey, Daniels grandfather. I hope this will be undertaken by either a local or national newspaper, or Radio/TV station.</p>
			<p>Whatever is raised through Operation Braveheart will be used to get not only personal items, but also some things to make life a little more bearable by way of home comforts for our brave hearts out there in theatre. A major part of any funding raised will be used to support those brave hearts that have been brought home maimed and injured, to help support their families and to support the families of those who have died for our country. Where needed, we will liaise with the Army Benevolent Fund, SSAFA and the British Legion as advisers?</p>
			<h2>HOW WILL YOU MAKE THIS HAPPEN?</h2>		
			<p>To make Operation Braveheart happen, and be the huge success that I hope and pray for and dream of, will be a huge logistical exercise. I need to reach out, and touch the hearts and minds of many in this country, and also many business people and supply companies, to appeal to them directly for their most gracious help and support, and indeed I would ask for your own personal prayers, to make all of this happen.</p>		
			<p>Below are listed the many areas we will need to cover if we are going to raise the necessary funding to support our servicemen and women out in the theatre and at home.</p>
			<h2>THE POPSTARS, BANDS, CELEBRITIES AND MPs</h2>
			<p>The first priority for Operation Braveheart is to be able to find the necessary contacts for the singers and bands, and to speak with them directly to appeal for their help in giving of their time and great talents to come and play and sing at the relevant venues. To do this I need to have the support of the TV &amp; Radio media and national newspapers that do have the contacts that will be needed. We are already starting on this first step to set wheels in motion. Contact will be made with the many MP's in the commons with the help of our own local MP's. WE NEED THE SUPPORT OF ALL THESE, FOR OPERATION BRAVEHEART TO BE A SUCCESS.</p>
			<h2>THE VENUES</h2>	
			<p>The venues will be wide spread and I hope to enlist the help of theaters and schools, football stadiums, in fact anywhere where large numbers of people can be accommodated</p>
			<h2>EQUIPMENT NEEDS</h2>
			<p>Various companies will need to be contacted for the many items of equipment that will be needed by the bands, singers and celebrities. These include staging, lighting and sound equipment for the bands to plug their various instruments into.</p>
			<p>Also needed will be transport to ship the items of equipment to the venues, a very necessary area of support indeed to keep everything on track.</p>
			<h2>VOLUNTEERS, HELPERS AND SUPPORTERS</h2>
			<p>If this is going to happen at all I will need a team, of volunteers, helpers and supporters (LOTS OF THEM) willing to help, and share the load, which will in turn light up the sky to show the world that the British public are indeed like our servicemen and women, A FORCE TO BE RECKONED WITH WHEN THE GOING GETS TOUGH.</p>	
			<p>Everyone, everywhere in some way can help, please don't think that you are to insignificant to matter, or have nothing to offer, on the contrary, every man, every woman and every child that raises a voice in support of our servicemen and women will be as great an asset to them as they indeed are to us.</p>
			<h2>MEDIA SUPPORT</h2>
			<p>The support of the media is uppermost in my mind, because they too have a vital role to play in the success of Operation Braveheart, because we have to reach out and TELL the people what is happening, we NEED the caring support of the British public to make it all happen.</p>
			<p>Both Radio and Television Stations will be contacted in the weeks ahead in 2008 to gain their support, as I would especially want some of these events to be televised and beamed out to the guys and girls out there in Iraq and Afghanistan.</p>
			<p>All National and Local newspapers will be contacted through my friends at the press association, for they will reach the letter boxes that other means cannot reach. I appeal directly to our media PLEASE HELP MAKE THIS HAPPEN.</p>
			<h2>FINALLY, AND IN CONCLUSION</h2>
			<p>The final frontier, the ultimate last and final step will be YOU! The public, for on you hinges everything that Operation Braveheart stands for. With your help, care and support we will BRING TRUTH AND JUSTICE FOR OUR WONDERFUL SERVICEMEN AND WOMEN, our most treasured and needed assets, both in times of peace and in times of war.</p>
			<p>I had the highest of honour, and greatest privilege at the time of our Daniels funeral to have met officers and men of Daniels regiment 2 Rifles who had flown back especially to be here for Daniel as he was lain to rest. To have heard of some of the things that they daily faced was very, very harrowing, and to hear of some of their needs was none less than soul destroying, and yes, it filled me with anger, but a righteous anger, for how can any country let down the front line of support in dire and dangerous times as this country has in these last four years.</p>
			<p>On the 27th February 2008 it will be one year on since we lost our devoted son and grandson, one year, that feels like a lifetime, and I have to tell you that that fire, that righteous anger, burns as an eternal flame to not only Daniels memory, but to the memory of all those who have given their lives on the cross, which is Iraq and Afghanistan today, and who daily, face a hidden and unseen enemy.</p>
		</div>
	</div>
</div>